import { t } from "../../include/text_strings"

export const seg2_course_name_table = [
    t(" 1 BOB-OMB BATTLEFIELD"),
   t(" 2 WHOMP'S FORTRESS"),
   t(" 3 JOLLY ROGER BAY"),
   t(" 4 COOL, COOL MOUNTAIN"),
   t(" 5 BIG BOO'S HAUNT"),
   t(" 6 HAZY MAZE CAVE"),
   t(" 7 LETHAL LAVA LAND"),
   t(" 8 SHIFTING SAND LAND"),
   t(" 9 DIRE, DIRE DOCKS"),
   t("10 SNOWMAN'S LAND"),
   t("11 WET-DRY WORLD"),
   t("12 TALL, TALL MOUNTAIN"),
   t("13 TINY-HUGE ISLAND"),
   t("14 TICK TOCK CLOCK"),
   t("15 RAINBOW RIDE"),
   t("   BOWSER IN THE DARK WORLD"),
   t("   BOWSER IN THE FIRE SEA"),
   t("   BOWSER IN THE SKY"),
   t("   THE PRINCESS'S SECRET SLIDE"),
   t("   CAVERN OF THE METAL CAP"),
   t("   TOWER OF THE WING CAP"),
   t("   VANISH CAP UNDER THE MOAT"),
   t("   WING MARIO OVER THE RAINBOW"),
   t("   THE SECRET AQUARIUM"),
   t(""),
   t("   CASTLE SECRET STARS"),
   t("ONE OF THE CASTLE'S SECRET STARS!"),
   t(""),
   t(""),
   t(""),
   t(""),
   t(""),
   t(""),
]

export const seg2_act_name_table = [
   t("BIG BOB-OMB ON THE SUMMIT"),
   t("FOOTRACE WITH KOOPA THE QUICK"),
   t("SHOOT TO THE ISLAND IN THE SKY"),
   t("FIND THE 8 RED COINS"),
   t("MARIO WINGS TO THE SKY"),
   t("BEHIND CHAIN CHOMP'S GATE"),
    
]